OnlineCodex/OnlineCodex

- .travis.yml
Adds SonarCloud support through travis.
> Add SonarCloud support

- pom.xml
- src/main/java/oc/OnlineCodex.java
- src/main/java/oc/VersionChecker.java
- src/main/java/oc/utils/DesktopUtils.java
- src/main/java/oc/utils/GitHubUtils.java
- src/main/java/oc/utils/ManifestUtils.java
> 15 implement version reminder

- src/main/java/oc/wh40k/units/or/ORBattlewagon.java
- src/main/java/oc/wh40k/units/or/ORBonebreaka.java
- src/main/java/oc/wh40k/units/or/ORGunwagon.java
- src/main/java/oc/wh40k/units/or/ORKommandos.java
- src/main/java/oc/wh40k/units/or/ORWaffenUndGeschenke.java
- src/main/resources/oc/wh40k/indices/or.csv
> 37 ork bugs

- src/main/java/oc/BuildaTextArea.java
- src/main/java/oc/Eintrag.java
> Add power level information to detachments and units in the generated army list

- src/main/java/oc/OptionsUpgradeGruppe.java
- src/main/java/oc/wh40k/units/or/ORWaffenUndGeschenke.java
> Changed clan condition for "Da Fixer Upper"

- src/main/java/oc/wh40k/armies/VOLKOrks.java
Moved index HQs to the end of the list.
Combined clan lists that contain the same units.
Fix issue #50
> Added Kaptin Badrukk to all ork clans

- src/main/java/oc/wh40k/units/or/ORBurnaBoyz.java
> Correct powerlevel for burna boyz

- src/main/java/oc/wh40k/armies/VOLKImperium.java
> Add FW options for SM chapters

- src/main/java/oc/wh40k/units/or/ORDeffDreadKammer.java
Standard weapons and options are now separated groups.
Selected options automaticly decrease selected standard options.
Fix issue #62
> Changed deffdread weapon selection

- src/main/java/oc/wh40k/armies/VOLKAeldari.java
> Added Kabals, Wych Cults and Haemonculus Covens

- src/main/java/oc/wh40k/armies/VOLKOrks.java
- src/main/java/oc/wh40k/units/or/ORNobz.java
- src/main/java/oc/wh40k/units/or/ORNobzonWarbikes.java
- src/main/java/oc/wh40k/units/or/ORWaffenUndGeschenke.java
> 66 ork bugs

- src/main/java/oc/wh40k/units/ae/AEWarlockSkyrunner.java
> Corrected single warlock skyrunner points

- src/main/java/oc/wh40k/units/or/ORWaffenUndGeschenke.java
> Corrects warbiker nob bug

- src/main/java/oc/wh40k/units/ch/CHHellforgedContemptorDreadnought.java
- src/main/java/oc/wh40k/units/ch/CHHellforgedLeviathanDreadnought.java
> Corrected secondary weapon selection

- src/main/java/oc/wh40k/armies/VOLKChaos.java
> Mark CSM index units

- src/main/java/oc/wh40k/units/im/IMDeathwatchTerminatorSquad.java
- src/main/java/oc/wh40k/units/im/IMDeathwatchVeterans.java
- src/main/java/oc/wh40k/units/im/IMKillteamKammer.java
> 8 deathwatch bugs

- src/main/java/oc/wh40k/armies/VOLKTyraniden.java
- src/main/java/oc/wh40k/units/im/IMWarlordtraits.java
- src/main/java/oc/wh40k/units/or/ORWarlordtraits.java
- src/main/java/oc/wh40k/units/ty/TYBroodlord.java
- src/main/java/oc/wh40k/units/ty/TYHiveTyrant.java
- src/main/java/oc/wh40k/units/ty/TYNeurotrophe.java
- src/main/java/oc/wh40k/units/ty/TYRuestkammer.java
- src/main/java/oc/wh40k/units/ty/TYTervigon.java
- src/main/java/oc/wh40k/units/ty/TYTrygonPrime.java
- src/main/java/oc/wh40k/units/ty/TYWarlordtraits.java
> 59 complete tyranids

- src/main/java/oc/BuildaHQ.java
- src/main/java/oc/BuildaVater.java
- src/main/java/oc/wh40k/armies/VOLKImperium.java
- src/main/java/oc/wh40k/units/im/IMCaladiusGravTank.java
- src/main/java/oc/wh40k/units/im/IMContemptorAchillusDreadnought.java
- src/main/java/oc/wh40k/units/im/IMContemptorExemplarDreadnought.java
- src/main/java/oc/wh40k/units/im/IMCoronusGravCarrier.java
- src/main/java/oc/wh40k/units/im/IMRelicLeviathanDreadnought.java
- src/main/resources/oc/wh40k/indices/iaaa.csv
- src/main/resources/oc/wh40k/indices/sm.csv
Fix issue #85 
Fix issue #82 
Also corrected point values in the same points files and added [FW] tags for other units of the same source book.
> 85 Imperial Armour Adeptus Astartes issues

- src/main/java/oc/wh40k/units/ch/CHRenegadeArmiger.java
> Change weapon group 1 to counter

- src/main/java/oc/wh40k/armies/VOLKImperium.java
> Corrected typo

- src/main/java/oc/BuildaVater.java
> Add decdicated transports for the supreme command detachment

- src/main/java/oc/wh40k/units/ty/TYMalanthrope.java
> Add warlord traits for the Malantrophe

- src/main/java/oc/wh40k/units/ch/CHWaffenkammer.java
> 97 Add force stave for the Sorcerer. Remove one force sword

- src/main/java/oc/wh40k/units/ch/CHFiendsofSlaanesh.java
- src/main/java/oc/wh40k/units/ch/CHFleshHounds.java
- src/main/resources/oc/wh40k/indices/ae.yaml
- src/main/resources/oc/wh40k/indices/ami.yaml
- src/main/resources/oc/wh40k/indices/chaos.yaml
- src/main/resources/oc/wh40k/indices/sw.yaml
- src/main/resources/oc/wh40k/indices/taaa.yaml
- src/main/resources/oc/wh40k/indices/ty.yaml
Fix issue #106 
Fix issue #114
> 106 add missing point updates for ca2018

- src/main/java/oc/wh40k/armies/VOLKChaos.java
- src/main/java/oc/wh40k/armies/VOLKImperium.java
- src/main/java/oc/wh40k/units/ch/CHTerraxPatternTermiteAssaultDrill.java
- src/main/java/oc/wh40k/units/im/IMAdeptusMechanicusRuestkammer.java
- src/main/java/oc/wh40k/units/im/IMSecutariiHoplites.java
- src/main/java/oc/wh40k/units/im/IMSecutariiPeltasts.java
- src/main/java/oc/wh40k/units/im/IMSicarianRuststalkers.java
- src/main/java/oc/wh40k/units/im/IMSkitariiRangers.java
- src/main/java/oc/wh40k/units/im/IMSkitariiVanguard.java
- src/main/java/oc/wh40k/units/im/IMTerraxPatternTermiteAssaultDrill.java
- src/main/resources/oc/wh40k/indices/ame.yaml
- src/main/resources/oc/wh40k/indices/chaos.yaml
- src/main/resources/oc/wh40k/indices/sm.yaml
Added Termite drill, Hoplites and Peltasts.
https://github.com/OnlineCodex/OnlineCodex/issues/78
> Added missing units, Termite Drill, Hoplites, Peltasts

- src/main/java/oc/wh40k/armies/VOLKImperium.java
> 121 Added Missing units to Imperial Regiments

- src/main/resources/oc/wh40k/indices/sm.yaml
> Corrected cenobyte servitor points

- src/main/java/oc/wh40k/armies/VOLKImperium.java
- src/main/java/oc/wh40k/units/im/IMDeathwatchVeterans.java
- src/main/resources/oc/wh40k/indices/dw.yaml
> Point corrections + FW units

- src/main/java/oc/wh40k/units/ta/TACommanderinXV85EnforcerBattlesuit.java
- src/main/java/oc/wh40k/units/ta/TACommanderinXV86ColdstarBattlesuit.java
- src/main/java/oc/wh40k/units/ta/TACommanderinXV8CrisisBattlesuit.java
- src/main/java/oc/wh40k/units/ta/TAKampfanzugKammer.java
- src/main/java/oc/wh40k/units/ta/TAXV8CrisisBattlesuits.java
Also Fixed some minor bugs I saw on the way.
Fix issue #127
> Fixed wargear reset after reload for coldstar

- src/main/java/oc/wh40k/units/im/IMAstraMilitarumMeleeWeapons.java
- src/main/java/oc/wh40k/units/im/IMAstraMilitarumRuestkammer.java
- src/main/java/oc/wh40k/units/im/IMChimera.java
> 154 astra militarum bugs

- src/main/java/oc/wh40k/units/ch/CHDaemonPrinceofNurgle.java
- src/main/java/oc/wh40k/units/ch/CHDaemonPrinceofNurglewithWings.java
- src/main/java/oc/wh40k/units/ch/CHTyphus.java
> Added Warlord traits for Daemon prince of Nurgle + corrected Typhus

- src/main/resources/oc/wh40k/indices/am.yaml
> corrected price for exterminator autocannon

- src/main/java/oc/wh40k/units/im/IMRunePriestinTerminatorArmour.java
> fixed rune priest name
